CREATE TABLE IF NOT EXISTS VK_Partners (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    partner_id VARCHAR(20) NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT False,
    ban BOOLEAN NOT NULL DEFAULT False
);

CREATE TABLE IF NOT EXISTS VK_Photos (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    partner_id VARCHAR(20) NOT NULL,
    photo_link VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS VK_Settings (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    conf_name VARCHAR(20) NOT NULL,
    conf_value VARCHAR(100) NOT NULL
);